# Synthetic Mental Health Reddit Posts Dataset
# Generated automatically using Claude Sonnet 4
# Each post is scored for various mental health conditions (0.0 - 1.0)

post_data = [
    {
        "text": 'Just finished a 5K run this morning! Feeling energized and ready to tackle the week ahead.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Movie night with the family was perfect. Sometimes the simple things are the best things in life.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Got promoted today! All those late nights finally paid off. Celebrating with my favorite restaurant tonight.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Beautiful sunset from my backyard. Grateful for moments like these.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Weekend farmers market haul! Excited to try some new recipes this week.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Finished reading an amazing book today. Love getting lost in a good story.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Coffee date with my best friend was exactly what I needed. Good friends make everything better.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'My garden is finally blooming! Spring always fills me with hope and joy.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": "Learned a new guitar chord today. Progress feels good, even when it's small.",
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": "Team lunch was so fun today. I'm lucky to work with such great people.",
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Volunteering at the animal shelter always brightens my day. These dogs are pure joy.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Date night was perfect! 10 years together and still having fun.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Yoga class this morning left me feeling centered and peaceful. Great way to start Monday.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Kids are finally asleep and I have some me-time. Simple pleasures.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Hiking trail was gorgeous today. Nature therapy is the best therapy.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Homemade pizza turned out amazing! Cooking experiments that actually work are the best.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Concert last night was incredible. Live music just hits different.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Productive day at work and now relaxing with a good show. Balance feels right.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Beach day with the family was perfect. Sun, sand, and good vibes.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Finally organized my closet! Small accomplishments that make me happy.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Game night with friends was hilarious. Laughed until my stomach hurt.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Morning meditation session felt really good today. Starting to see the benefits.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Farmers market and brunch with mom. Quality time is everything.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'New art class starts tomorrow! Excited to try something creative and different.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Cozy rainy day with hot tea and a good book. Sometimes staying in is perfect.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Dog park adventures with my pup. He makes friends easier than I do!',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Finished a challenging project at work today. Feeling accomplished and ready for the weekend.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Dinner party was a success! Love hosting friends and trying new recipes.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Saturday morning bike ride through the park. Fresh air and exercise = perfect combo.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": 'Museum visit was fascinating today. Always love learning something new.',
        "depression": 0.0,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.0
    },
    {
        "text": "Feeling a bit nervous about tomorrow's job interview, but trying to stay positive.",
        "depression": 0.1,
        "anxiety": 0.3,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.3
    },
    {
        "text": "Monday blues hitting a little harder than usual today. Coffee isn't helping much.",
        "depression": 0.3,
        "anxiety": 0.1,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.3
    },
    {
        "text": 'Having trouble concentrating at work today. Mind keeps wandering to random things.',
        "depression": 0.0,
        "anxiety": 0.1,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.4,
        "overall_score": 0.3
    },
    {
        "text": 'Feeling a little overwhelmed with everything on my plate right now. Need to prioritize better.',
        "depression": 0.2,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.2,
        "overall_score": 0.4
    },
    {
        "text": "Social event tonight and I'm already feeling drained thinking about it. Maybe I'll skip.",
        "depression": 0.2,
        "anxiety": 0.3,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.3
    },
    {
        "text": 'Been procrastinating on this project all week. Why is it so hard to just start?',
        "depression": 0.2,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.4,
        "overall_score": 0.4
    },
    {
        "text": 'Ate too much junk food this weekend, feeling a bit gross about it now.',
        "depression": 0.1,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.3,
        "adhd": 0.0,
        "overall_score": 0.3
    },
    {
        "text": "Sleep schedule is completely messed up. Probably shouldn't have had that late coffee.",
        "depression": 0.1,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.3,
        "overall_score": 0.3
    },
    {
        "text": 'Feeling a bit lonely lately. Maybe I should reach out to friends more often.',
        "depression": 0.3,
        "anxiety": 0.1,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.3
    },
    {
        "text": 'Work presentation went okay, but I keep replaying all the parts I messed up.',
        "depression": 0.1,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.4
    },
    {
        "text": 'Motivation is pretty low today. Just going through the motions.',
        "depression": 0.4,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.1,
        "overall_score": 0.4
    },
    {
        "text": "Forgot three important things today already. Brain feels like it's not working right.",
        "depression": 0.1,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.4,
        "overall_score": 0.4
    },
    {
        "text": 'Family dinner was stressful. Why do these gatherings always feel like walking on eggshells?',
        "depression": 0.2,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.4
    },
    {
        "text": "Been avoiding the gym for two weeks now. Just don't feel like doing anything active.",
        "depression": 0.3,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.1,
        "adhd": 0.0,
        "overall_score": 0.3
    },
    {
        "text": 'Overthinking everything again. Wish I could just turn my brain off sometimes.',
        "depression": 0.2,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.2,
        "overall_score": 0.4
    },
    {
        "text": 'Feeling irritable for no real reason today. Everything is annoying me.',
        "depression": 0.2,
        "anxiety": 0.1,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.3,
        "eating_disorder": 0.0,
        "adhd": 0.2,
        "overall_score": 0.3
    },
    {
        "text": "Can't decide what to wear, what to eat, or what to do. Decision fatigue is real.",
        "depression": 0.2,
        "anxiety": 0.3,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.3,
        "overall_score": 0.4
    },
    {
        "text": 'Scrolled social media for hours instead of being productive. Feel worse now than when I started.',
        "depression": 0.3,
        "anxiety": 0.1,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.3,
        "overall_score": 0.3
    },
    {
        "text": "Worried about money again. Bills keep piling up and I'm not sure how to handle it all.",
        "depression": 0.3,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.4
    },
    {
        "text": "Snapped at my partner over something small. Feel bad about it but couldn't control my reaction.",
        "depression": 0.2,
        "anxiety": 0.1,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.2,
        "eating_disorder": 0.0,
        "adhd": 0.3,
        "overall_score": 0.3
    },
    {
        "text": "Heart keeps racing for no reason. Probably just too much caffeine but it's making me anxious.",
        "depression": 0.0,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.1,
        "overall_score": 0.4
    },
    {
        "text": "Canceled plans again tonight. I want to be social but when the time comes, I just can't.",
        "depression": 0.3,
        "anxiety": 0.3,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.3
    },
    {
        "text": 'Everything feels like it requires so much effort today. Even simple tasks feel overwhelming.',
        "depression": 0.4,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.1,
        "overall_score": 0.4
    },
    {
        "text": 'Been comparing myself to everyone on social media again. Why do I do this to myself?',
        "depression": 0.3,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.3,
        "adhd": 0.0,
        "overall_score": 0.3
    },
    {
        "text": "Imposter syndrome hitting hard at work today. Feel like everyone will realize I don't know what I'm doing.",
        "depression": 0.2,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.4
    },
    {
        "text": "Room is a complete mess and I can't seem to find the energy to clean it. It's making me feel worse.",
        "depression": 0.4,
        "anxiety": 0.1,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.3,
        "overall_score": 0.4
    },
    {
        "text": "Skipped breakfast and lunch again. Not intentionally, just keep forgetting to eat when I'm busy.",
        "depression": 0.1,
        "anxiety": 0.0,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.3,
        "adhd": 0.4,
        "overall_score": 0.3
    },
    {
        "text": "Feeling restless and can't sit still. Need to move around but don't know what I want to do.",
        "depression": 0.0,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.3,
        "eating_disorder": 0.0,
        "adhd": 0.4,
        "overall_score": 0.3
    },
    {
        "text": "Another sleepless night staring at the ceiling. Mind won't stop racing about tomorrow's tasks.",
        "depression": 0.2,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.3,
        "overall_score": 0.4
    },
    {
        "text": 'Therapy session was tough but necessary. Working through some difficult emotions right now.',
        "depression": 0.5,
        "anxiety": 0.3,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.5
    },
    {
        "text": 'Three weeks without a panic attack. Small victories but they mean everything to me.',
        "depression": 0.2,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.5
    },
    {
        "text": 'Started medication for ADHD last month. Still adjusting but already noticing some improvements in focus.',
        "depression": 0.1,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.6,
        "overall_score": 0.5
    },
    {
        "text": "Bad day but I managed to shower and eat something. Recovery isn't linear and that's okay.",
        "depression": 0.6,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.6
    },
    {
        "text": 'Anxiety is manageable today with breathing exercises. Tools from therapy are actually helping.',
        "depression": 0.2,
        "anxiety": 0.5,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.5
    },
    {
        "text": 'Mood has been all over the place this week. Up and down like a roller coaster.',
        "depression": 0.3,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.6,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.6
    },
    {
        "text": "Eating disorder thoughts are loud today but I'm fighting them. Called my therapist for support.",
        "depression": 0.3,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.6,
        "adhd": 0.0,
        "overall_score": 0.6
    },
    {
        "text": 'Flashbacks from the car accident interrupted my work meeting again. Need to talk to someone about this.',
        "depression": 0.2,
        "anxiety": 0.4,
        "ptsd": 0.6,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.6
    },
    {
        "text": "Can't concentrate on anything today. Brain feels scattered and unfocused no matter what I try.",
        "depression": 0.3,
        "anxiety": 0.3,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.6,
        "overall_score": 0.5
    },
    {
        "text": "Support group meeting helped today. Knowing others understand what I'm going through makes a difference.",
        "depression": 0.4,
        "anxiety": 0.3,
        "ptsd": 0.3,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.5
    },
    {
        "text": 'Manic episode hit last night. Stayed up until 4am reorganizing my entire closet and spent way too much online.',
        "depression": 0.0,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.6,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.6
    },
    {
        "text": "Intrusive thoughts are really bothering me today. Trying to remind myself they're just thoughts, not reality.",
        "depression": 0.3,
        "anxiety": 0.5,
        "ptsd": 0.2,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.5
    },
    {
        "text": 'Finally reached out to a therapist after months of putting it off. First appointment is next week.',
        "depression": 0.5,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.5
    },
    {
        "text": "Hypervigilant all day after that news story. Can't shake the feeling that something bad is going to happen.",
        "depression": 0.2,
        "anxiety": 0.4,
        "ptsd": 0.6,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.6
    },
    {
        "text": 'Medication adjustment is rough. Side effects are hard but hoping it helps in the long run.',
        "depression": 0.4,
        "anxiety": 0.3,
        "ptsd": 0.0,
        "schizophrenia": 0.2,
        "bipolar": 0.3,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.5
    },
    {
        "text": "Avoided mirrors all day. Body dysmorphia is hitting hard and I can't handle seeing myself right now.",
        "depression": 0.4,
        "anxiety": 0.3,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.6,
        "adhd": 0.0,
        "overall_score": 0.6
    },
    {
        "text": "Executive dysfunction is real today. Know what I need to do but can't make myself do any of it.",
        "depression": 0.3,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.6,
        "overall_score": 0.5
    },
    {
        "text": "Grounding techniques helped during today's panic attack. 5-4-3-2-1 method actually worked.",
        "depression": 0.1,
        "anxiety": 0.6,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.5
    },
    {
        "text": "Depression is winning today but I'm still here. That has to count for something.",
        "depression": 0.6,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.6
    },
    {
        "text": "Nightmare about the incident woke me up again. Sleep feels impossible when my brain won't let me rest.",
        "depression": 0.3,
        "anxiety": 0.4,
        "ptsd": 0.6,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.6
    },
    {
        "text": 'Impulsive spending spree yesterday during a mood swing. Credit card bill is going to hurt.',
        "depression": 0.2,
        "anxiety": 0.3,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.5,
        "eating_disorder": 0.0,
        "adhd": 0.3,
        "overall_score": 0.5
    },
    {
        "text": "Ate a full meal for the first time in days. Recovery is hard but I'm trying to be gentle with myself.",
        "depression": 0.3,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.5,
        "adhd": 0.0,
        "overall_score": 0.5
    },
    {
        "text": 'Social anxiety made me leave the party early again. Disappointed in myself but also relieved to be home.',
        "depression": 0.3,
        "anxiety": 0.6,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.6
    },
    {
        "text": 'Sensory overload at the grocery store today. Too many sounds, lights, and people. Had to leave without shopping.',
        "depression": 0.2,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.5,
        "overall_score": 0.5
    },
    {
        "text": 'Therapy homework is challenging but necessary. Working on trauma processing is exhausting but important.',
        "depression": 0.3,
        "anxiety": 0.3,
        "ptsd": 0.5,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.5
    },
    {
        "text": 'Medication is helping with the voices but the side effects are really tough to deal with.',
        "depression": 0.3,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.5,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.5
    },
    {
        "text": "Can't get out of bed today. Everything feels impossible and pointless right now.",
        "depression": 0.8,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.8
    },
    {
        "text": 'The voices are getting louder and more persistent. Need to call my psychiatrist immediately.',
        "depression": 0.2,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.9,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.9
    },
    {
        "text": "Panic attack lasted for hours last night. Thought I was dying. ER couldn't find anything wrong physically.",
        "depression": 0.3,
        "anxiety": 0.9,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.9
    },
    {
        "text": "Haven't eaten in three days. Know I should but the thought of food makes me sick.",
        "depression": 0.4,
        "anxiety": 0.3,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.9,
        "adhd": 0.0,
        "overall_score": 0.9
    },
    {
        "text": "Flashbacks are so vivid I can't tell what's real anymore. Living in constant fear.",
        "depression": 0.5,
        "anxiety": 0.6,
        "ptsd": 1.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 1.0
    },
    {
        "text": "Manic episode has me convinced I can do anything. Quit my job and maxed out credit cards. This isn't good.",
        "depression": 0.0,
        "anxiety": 0.1,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.9,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.9
    },
    {
        "text": "Suicidal thoughts won't stop. Called the crisis line but still feel so alone and hopeless.",
        "depression": 1.0,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 1.0
    },
    {
        "text": "Dissociating so badly I lost three hours today. Don't remember driving home from work.",
        "depression": 0.4,
        "anxiety": 0.5,
        "ptsd": 0.8,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.8
    },
    {
        "text": "Hallucinations are getting worse. Seeing things that aren't there and it's terrifying me.",
        "depression": 0.3,
        "anxiety": 0.6,
        "ptsd": 0.0,
        "schizophrenia": 0.8,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.8
    },
    {
        "text": "Self-harm urges are overwhelming tonight. Trying to distract myself but it's so hard.",
        "depression": 0.8,
        "anxiety": 0.5,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.4,
        "adhd": 0.0,
        "overall_score": 0.8
    },
    {
        "text": 'Psychotic break happened at work. Ambulance came and everyone saw. Feel so ashamed and scared.',
        "depression": 0.5,
        "anxiety": 0.7,
        "ptsd": 0.0,
        "schizophrenia": 0.9,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.9
    },
    {
        "text": "Binge and purge cycle is completely out of control. Body is shutting down but I can't stop.",
        "depression": 0.6,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 1.0,
        "adhd": 0.0,
        "overall_score": 1.0
    },
    {
        "text": "Paranoid delusions are consuming my thoughts. Everyone feels like a threat. Can't leave the house.",
        "depression": 0.4,
        "anxiety": 0.8,
        "ptsd": 0.0,
        "schizophrenia": 0.8,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.8
    },
    {
        "text": "Severe depression episode. Haven't showered in a week. Can barely function enough to feed myself.",
        "depression": 0.9,
        "anxiety": 0.2,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.0,
        "overall_score": 0.9
    },
    {
        "text": "ADHD symptoms are destroying my life. Lost another job because I can't focus or remember anything.",
        "depression": 0.5,
        "anxiety": 0.4,
        "ptsd": 0.0,
        "schizophrenia": 0.0,
        "bipolar": 0.0,
        "eating_disorder": 0.0,
        "adhd": 0.8,
        "overall_score": 0.8
    },
